-- DB_VACCIN
CREATE DATABASE DB_VACCIN;
USE DB_VACCIN;

-- (회원 테이블)
CREATE TABLE TBL_USER_MEMBER(
M_ID      		VARCHAR(20)   	PRIMARY KEY     COMMENT'회원ID',
M_PW      		VARCHAR(20)   	NOT NULL      	COMMENT'회원PW',
M_MAIL      	VARCHAR(20)               		COMMENT'회원MAIL',
M_PHONE      	VARCHAR(20)               		COMMENT'회원PHONE',
SC_NUMBER   	VARCHAR(20)   	NOT NULL      	COMMENT'주민번호',
M_REG_DATE   	TIMESTAMP    	DEFAULT NOW()   COMMENT'등록일',
M_MOD_DATE   	TIMESTAMP   	DEFAULT NOW()   COMMENT'수정일',
M_IS_ACTIVE 	BOOLEAN			DEFAULT TRUE	COMMENT'회원정보 활성화 여부'
);

SELECT * FROM TBL_USER_MEMBER;
DROP TABLE TBL_USER_MEMBER;

-- (백신 접종 현황테이블)
CREATE TABLE TBL_FLU_VACCIN_PERSON(
   FVP_NO         INT         AUTO_INCREMENT         COMMENT'접종NO',
   FVP_NAME      VARCHAR(30)   NOT NULL            COMMENT'접종자이름',
   SC_NUMBER      VARCHAR(20)   NOT NULL            COMMENT'주민번호',
   FVP_MAIL      VARCHAR(30)   NOT NULL            COMMENT'접종자MAIL',
   FVP_PHONE      VARCHAR(30)   NOT NULL            COMMENT'접종자PHONE',
   FV_LOCATION_NO   INT         NOT NULL            COMMENT'접종처NO',
   FV_TYPE_NO      INT                           COMMENT'백신NO',
   FVP_REG_DATE   TIMESTAMP DEFAULT NOW()            COMMENT'등록일',
   FVP_MOD_DATE   TIMESTAMP DEFAULT NOW()            COMMENT'수정일',
   PRIMARY KEY(FVP_NO) 
);

SELECT * FROM TBL_FLU_VACCIN_PERSON;
DROP TABLE TBL_FLU_VACCIN_PERSON;

-- (주민등록번호 테이블)
CREATE TABLE TBL_SOCIAL_NUMBER(
   SC_NUMBER   VARCHAR(20)                   COMMENT'주민번호',
   SC_NAME      VARCHAR(20)   NOT NULL            COMMENT'이름',
   SC_ADDR      VARCHAR(50)   NOT NULL            COMMENT'주소',
   SC_PHONE   VARCHAR(20)   NOT NULL            COMMENT'연락처',
   SC_REG_DATE   TIMESTAMP DEFAULT NOW()            COMMENT'등록일',
   SC_MOD_DATE   TIMESTAMP DEFAULT NOW()            COMMENT'수정일',
   PRIMARY KEY(SC_NUMBER) 
);

SELECT * FROM TBL_SOCIAL_NUMBER;
DROP TABLE TBL_SOCIAL_NUMBER;

INSERT INTO TBL_SOCIAL_NUMBER(SC_NUMBER, SC_NAME, SC_ADDR, SC_PHONE) 
VALUES('720520-1018547', '홍길동', 'AAA시 BBB구 CCC동 123-10', '010-458-8541');
INSERT INTO TBL_SOCIAL_NUMBER(SC_NUMBER, SC_NAME, SC_ADDR, SC_PHONE) 
VALUES('710210-2084561', '박찬호', 'DDD시 EEE구 FFF동 456-20', '010-412-9514');
INSERT INTO TBL_SOCIAL_NUMBER(SC_NUMBER, SC_NAME, SC_ADDR, SC_PHONE) 
VALUES('941230-1075214', '박세리', 'GGG시 HHH구 III동 789-30', '010-958-7536');
INSERT INTO TBL_SOCIAL_NUMBER(SC_NUMBER, SC_NAME, SC_ADDR, SC_PHONE) 
VALUES('650215-2050128', '이병규', 'JJJ시 KKK구 LLL동 987-40', '010-528-1478');
INSERT INTO TBL_SOCIAL_NUMBER(SC_NUMBER, SC_NAME, SC_ADDR, SC_PHONE) 
VALUES('800710-1025698', '손흥민', 'MMM시 NNN구 OOO동 654-50', '010-296-5236');

-- (백신 접종처 테이블)
CREATE TABLE TBL_FV_LOCATION(
   FV_LOCATION_NO         INT                          COMMENT'접종처NO',
   FV_LOCATION_NAME      VARCHAR(20)   NOT NULL         COMMENT'접종처이름',
   FV_LOCATION_ADDR      VARCHAR(50)   NOT NULL         COMMENT'접종처주소',
   FV_LOCATION_PHONE      VARCHAR(20)   NOT NULL         COMMENT'접종처연락처',
   FV_LOCATION_MANAGER      VARCHAR(20)   NOT NULL         COMMENT'접종처담담당자',
   FV_LOCATION_REG_DATE   TIMESTAMP   DEFAULT NOW()      COMMENT'등록일',
   FV_LOCATION_MOD_DATE   TIMESTAMP   DEFAULT NOW()      COMMENT'수정일',
   PRIMARY KEY(FV_LOCATION_NO)  
);
INSERT INTO tbl_fv_location(FV_LOCATION_NO, FV_LOCATION_NAME, FV_LOCATION_ADDR, FV_LOCATION_PHONE,FV_LOCATION_MANAGER) 
VALUES(1001, 'A접종처', 'AAA시 aaa구 471-013', '010-8410-8426', 'A담당');
INSERT INTO tbl_fv_location(FV_LOCATION_NO, FV_LOCATION_NAME, FV_LOCATION_ADDR, FV_LOCATION_PHONE,FV_LOCATION_MANAGER) 
VALUES(1002, 'B접종처', 'BBB시 bbb구 789-123', '010-9147-8523', 'B담당');
INSERT INTO tbl_fv_location(FV_LOCATION_NO, FV_LOCATION_NAME, FV_LOCATION_ADDR, FV_LOCATION_PHONE,FV_LOCATION_MANAGER) 
VALUES(1003, 'C접종처', 'CCC시 ccc구 456-789', '010-6901-4785', 'C담당');
INSERT INTO tbl_fv_location(FV_LOCATION_NO, FV_LOCATION_NAME, FV_LOCATION_ADDR, FV_LOCATION_PHONE,FV_LOCATION_MANAGER) 
VALUES(1004, 'D접종처', 'DDD시 ddd구 120-345', '010-2369-0123', 'D담당');
INSERT INTO tbl_fv_location(FV_LOCATION_NO, FV_LOCATION_NAME, FV_LOCATION_ADDR, FV_LOCATION_PHONE,FV_LOCATION_MANAGER) 
VALUES(1005, 'E접종처', 'EEE시 eee구 678-901', '010-4782-9514', 'E담당');

SELECT * FROM TBL_FV_LOCATION;
DROP TABLE TBL_FV_LOCATION;

-- (백신 타입 테이블)
CREATE TABLE TBL_FV_TYPE(
FV_TYPE_NO         INT                     COMMENT'백신NO',
FV_TYPE            VARCHAR(1)   NOT NULL      COMMENT'백신타입',
FV_TYPE_MNF_CTR      VARCHAR(20)   NOT NULL      COMMENT'백신제조국',
FV_TYPE_MNF_DATE   VARCHAR(50)   NOT NULL      COMMENT'백신제조일',
FV_TYPE_REG_DATE   TIMESTAMP    DEFAULT NOW()   COMMENT'등록일',
FV_TYPE_MOD_DATE   TIMESTAMP    DEFAULT NOW()   COMMENT'수정일',
PRIMARY KEY(FV_TYPE_NO)  
);

INSERT INTO tbl_fv_type(FV_TYPE_NO, FV_TYPE, FV_TYPE_MNF_CTR, FV_TYPE_MNF_DATE) 
VALUES(1, 'A', '한국', '2023-01-10');
INSERT INTO tbl_fv_type(FV_TYPE_NO, FV_TYPE, FV_TYPE_MNF_CTR, FV_TYPE_MNF_DATE) 
VALUES(2, 'B', '미국', '2023-01-15');
INSERT INTO tbl_fv_type(FV_TYPE_NO, FV_TYPE, FV_TYPE_MNF_CTR, FV_TYPE_MNF_DATE) 
VALUES(3, 'C', '영국', '2023-02-07');
INSERT INTO tbl_fv_type(FV_TYPE_NO, FV_TYPE, FV_TYPE_MNF_CTR, FV_TYPE_MNF_DATE) 
VALUES(4, 'D', '스웨덴', '2023-01-17');
INSERT INTO tbl_fv_type(FV_TYPE_NO, FV_TYPE, FV_TYPE_MNF_CTR, FV_TYPE_MNF_DATE) 
VALUES(5, 'E', '덴마크', '2022-12-22');

SELECT * FROM TBL_FV_TYPE;
DROP TABLE TBL_FV_TYPE;

-- (관리자 회원 테이블)
CREATE TABLE TBL_ADMIN_MEMBER(
AM_ID   VARCHAR(20)      	PRIMARY KEY      	COMMENT'관리자ID',
AM_PW   VARCHAR(20)      	NOT NULL      	  	COMMENT'관리자PW',
AM_NAME	VARCHAR(20)		 	NOT NULL		  	COMMENT'관리자이름',
AM_REG_DATE   TIMESTAMP DEFAULT NOW()      		COMMENT'등록일',
AM_MOD_DATE   TIMESTAMP DEFAULT NOW()      		COMMENT'수정일'
);
INSERT INTO TBL_ADMIN_MEMBER(AM_ID, AM_PW, AM_NAME, AM_NAME) VALUES ('admin', '1234', '홍길동');

SELECT * FROM TBL_ADMIN_MEMBER;
DROP TABLE TBL_ADMIN_MEMBER;

-- (관리자 인증번호 테이블)
CREATE TABLE TBL_ADMIN_AUTH_CODE (
    AUTH_CODE_ID 			INT AUTO_INCREMENT PRIMARY KEY 		COMMENT '인증번호 ID',
    AUTH_CODE 				VARCHAR(20) NOT NULL 				COMMENT '관리자 인증번호',
    AUTH_CODE_CREATE_ADMIN 	VARCHAR(20) NOT NULL				COMMENT '인증번호 등록자',
    AUTH_CODE_IS_ACTIVE 	BOOLEAN DEFAULT TRUE 				COMMENT '인증번호 활성화 여부',
    AUTH_CODE_REG_DATE 		TIMESTAMP DEFAULT NOW() 			COMMENT '생성일',
    AUTH_CODE_MOD_DATE 		TIMESTAMP DEFAULT NOW()				COMMENT '수정일'
);

INSERT INTO TBL_ADMIN_AUTH_CODE (AUTH_CODE, AUTH_CODE_CREATE_ADMIN) VALUES ('GREEN', '홍길동');
SELECT * FROM TBL_ADMIN_AUTH_CODE;
DROP TABLE TBL_ADMIN_AUTH_CODE;

SELECT * FROM TBL_USER_MEMBER U
JOIN TBL_SOCIAL_NUMBER S
ON U.SC_NUMBER = S.SC_NUMBER
WHERE M_ID = 'gildong';


